query PoolsAtBlock($first: Int, $skip: Int, $block: Int) {
  pools(
    first: $first
    skip: $skip
    orderBy: id
    orderDirection: asc
    block: { number: $block }
  ) {
    address
    id
    symbol
    totalProtocolFeePaidInBPT
    tokens {
      symbol
      address
      paidProtocolFees
    }
  }
}
